In [1]:
import pandas as pd
import numpy as np
import matplotlib as pip
import seaborn as sis

import warnings
warnings.filterwarnings(action="ignore")

In [2]:
from sklearn.linear_model import LinearRegression
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler, PolynomialFeatures
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score

In [3]:
import os
print(os.getcwd())

C:\Users\Prakash

In [4]:
import os
print(os.listdir())

['.anaconda', '.android', '.bash_history', '.conda', '.continuum', '.copilot', '.gitconfig', '.gradle', '.ipynb_checkpoints', '.ipython', '.junie', '.jupyter', '.keras', '.matplotlib', '.virtual_documents', '.vscode', '.vscode-shared', '25-04.ipynb', 'anaconda3', 'AndroidStudioProjects', 'AppData', 'Application Data', 'catboost_info', 'Contacts', 'Cookies', 'Credit Card Fraud Detection.ipynb', 'DataScienceEcosystem.ipynb', 'Documents', 'Downloads', 'Favorites', 'fraud_model.pkl', 'IBM-Stock-Data-Dashboard.ipynb', 'IdeaProjects', 'IPL_final_score_predict.ipynb', 'librabies.ipynb', 'Links', 'Local Settings', 'Music', 'My Documents', 'my_app', 'NetHood', 'New folder', 'New folder (2)', 'NTUSER.DAT', 'ntuser.dat.LOG1', 'ntuser.dat.LOG2', 'NTUSER.DAT{c5feab71-9073-11f0-b65f-502e9107dfc9}.TM.blf', 'NTUSER.DAT{c5feab71-9073-11f0-b65f-502e9107dfc9}.TMContainer00000000000000000001.regtrans-ms', 'NTUSER.DAT{c5feab71-9073-11f0-b65f-502e9107dfc9}.TMContainer00000000000000000002.regtrans-ms', 'ntuser.ini', 'Numpy.ipynb', 'OneDrive', 'Pictures', 'PrintHood', 'project_2.ipynb', 'python.ipynb', 'pythonintroduction.pyind', 'Recent', 'Saved Games', 'Searches', 'SendTo', 'source', 'Start Menu', 'Templates', 'Untitled.ipynb', 'Untitled1.ipynb', 'Untitled10.ipynb', 'Untitled11.ipynb', 'Untitled12.ipynb', 'Untitled13.ipynb', 'Untitled14.ipynb', 'Untitled15.ipynb', 'Untitled16.ipynb', 'Untitled17.ipynb', 'Untitled18.ipynb', 'Untitled19.ipynb', 'Untitled2.ipynb', 'Untitled3.ipynb', 'Untitled4.ipynb', 'Untitled5.ipynb', 'Untitled6.ipynb', 'Untitled7.ipynb', 'Untitled8.ipynb', 'Untitled9.ipynb', 'Videos']

In [5]:
import os

for file in os.listdir():
    if file.endswith('.csv'):
        print(file)

In [6]:
url = "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/..."

In [7]:
import os

for root, dirs, files in os.walk(os.getcwd()):
    for file in files:
        if "housing" in file.lower():
            print(os.path.join(root, file))

C:\Users\Prakash\anaconda3\Lib\site-packages\sklearn\datasets\_california_housing.py
C:\Users\Prakash\anaconda3\Lib\site-packages\sklearn\datasets\descr\california_housing.rst
C:\Users\Prakash\anaconda3\Lib\site-packages\sklearn\datasets\tests\test_california_housing.py
C:\Users\Prakash\anaconda3\Lib\site-packages\sklearn\datasets\tests\__pycache__\test_california_housing.cpython-313.pyc
C:\Users\Prakash\anaconda3\Lib\site-packages\sklearn\datasets\__pycache__\_california_housing.cpython-313.pyc
C:\Users\Prakash\anaconda3\Lib\site-packages\statsmodels\tsa\holtwinters\tests\results\housing-data.csv
C:\Users\Prakash\anaconda3\pkgs\scikit-learn-1.7.2-py313h7f7e138_0\Lib\site-packages\sklearn\datasets\_california_housing.py
C:\Users\Prakash\anaconda3\pkgs\scikit-learn-1.7.2-py313h7f7e138_0\Lib\site-packages\sklearn\datasets\descr\california_housing.rst
C:\Users\Prakash\anaconda3\pkgs\scikit-learn-1.7.2-py313h7f7e138_0\Lib\site-packages\sklearn\datasets\tests\test_california_housing.py
C:\Users\Prakash\anaconda3\pkgs\scikit-learn-1.7.2-py313h7f7e138_0\Lib\site-packages\sklearn\datasets\tests\__pycache__\test_california_housing.cpython-313.pyc
C:\Users\Prakash\anaconda3\pkgs\scikit-learn-1.7.2-py313h7f7e138_0\Lib\site-packages\sklearn\datasets\__pycache__\_california_housing.cpython-313.pyc
C:\Users\Prakash\anaconda3\pkgs\statsmodels-0.14.5-py313h2cb717b_0\Lib\site-packages\statsmodels\tsa\holtwinters\tests\results\housing-data.csv

In [8]:
import pandas as pd

df = pd.read_csv(r"C:\Users\Prakash\Downloads\kc_house_data.csv.zip")
df.head()

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,7129300520,20141013T000000,221900.0,3,1.00,1180,5650,1.0,0,0,...,7,1180,0,1955,0,98178,47.5112,-122.257,1340,5650
1,6414100192,20141209T000000,538000.0,3,2.25,2570,7242,2.0,0,0,...,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639
2,5631500400,20150225T000000,180000.0,2,1.00,770,10000,1.0,0,0,...,6,770,0,1933,0,98028,47.7379,-122.233,2720,8062
3,2487200875,20141209T000000,604000.0,4,3.00,1960,5000,1.0,0,0,...,7,1050,910,1965,0,98136,47.5208,-122.393,1360,5000
4,1954400510,20150218T000000,510000.0,3,2.00,1680,8080,1.0,0,0,...,8,1680,0,1987,0,98074,47.6168,-122.045,1800,7503

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21613 entries, 0 to 21612
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id             21613 non-null  int64
 1   date           21613 non-null  object
 2   price          21613 non-null  float64
 3   bedrooms       21613 non-null  int64
 4   bathrooms      21613 non-null  float64
 5   sqft_living    21613 non-null  int64
 6   sqft_lot       21613 non-null  int64
 7   floors         21613 non-null  float64
 8   waterfront     21613 non-null  int64
 9   view           21613 non-null  int64
 10  condition      21613 non-null  int64
 11  grade          21613 non-null  int64
 12  sqft_above     21613 non-null  int64
 13  sqft_basement  21613 non-null  int64
 14  yr_built       21613 non-null  int64
 15  yr_renovated   21613 non-null  int64
 16  zipcode        21613 non-null  int64
 17  lat            21613 non-null  float64
 18  long           21613 non-null  float64
 19  sqft_living15  21613 non-null  int64
 20  sqft_lot15     21613 non-null  int64
dtypes: float64(5), int64(15), object(1)
memory usage: 3.5+ MB

In [10]:
df.tail()

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
21608,263000018,20140521T000000,360000.0,3,2.50,1530,1131,3.0,0,0,...,8,1530,0,2009,0,98103,47.6993,-122.346,1530,1509
21609,6600060120,20150223T000000,400000.0,4,2.50,2310,5813,2.0,0,0,...,8,2310,0,2014,0,98146,47.5107,-122.362,1830,7200
21610,1523300141,20140623T000000,402101.0,2,0.75,1020,1350,2.0,0,0,...,7,1020,0,2009,0,98144,47.5944,-122.299,1020,2007
21611,291310100,20150116T000000,400000.0,3,2.50,1600,2388,2.0,0,0,...,8,1600,0,2004,0,98027,47.5345,-122.069,1410,1287
21612,1523300157,20141015T000000,325000.0,2,0.75,1020,1076,2.0,0,0,...,7,1020,0,2008,0,98144,47.5941,-122.299,1020,1357

In [11]:

df.shape

(21613, 21)

In [12]:
df.dtypes

id                 int64
date              object
price            float64
bedrooms           int64
bathrooms        float64
sqft_living        int64
sqft_lot           int64
floors           float64
waterfront         int64
view               int64
condition          int64
grade              int64
sqft_above         int64
sqft_basement      int64
yr_built           int64
yr_renovated       int64
zipcode            int64
lat              float64
long             float64
sqft_living15      int64
sqft_lot15         int64
dtype: object

In [13]:
df.isnull().sum()

id               0
date             0
price            0
bedrooms         0
bathrooms        0
sqft_living      0
sqft_lot         0
floors           0
waterfront       0
view             0
condition        0
grade            0
sqft_above       0
sqft_basement    0
yr_built         0
yr_renovated     0
zipcode          0
lat              0
long             0
sqft_living15    0
sqft_lot15       0
dtype: int64

In [14]:
df.describe()

,id,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
count,2.161300e+04,2.161300e+04,21613.000000,21613.000000,21613.000000,2.161300e+04,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000,21613.000000
mean,4.580302e+09,5.400881e+05,3.370842,2.114757,2079.899736,1.510697e+04,1.494309,0.007542,0.234303,3.409430,7.656873,1788.390691,291.509045,1971.005136,84.402258,98077.939805,47.560053,-122.213896,1986.552492,12768.455652
std,2.876566e+09,3.671272e+05,0.930062,0.770163,918.440897,4.142051e+04,0.539989,0.086517,0.766318,0.650743,1.175459,828.090978,442.575043,29.373411,401.679240,53.505026,0.138564,0.140828,685.391304,27304.179631
min,1.000102e+06,7.500000e+04,0.000000,0.000000,290.000000,5.200000e+02,1.000000,0.000000,0.000000,1.000000,1.000000,290.000000,0.000000,1900.000000,0.000000,98001.000000,47.155900,-122.519000,399.000000,651.000000
25%,2.123049e+09,3.219500e+05,3.000000,1.750000,1427.000000,5.040000e+03,1.000000,0.000000,0.000000,3.000000,7.000000,1190.000000,0.000000,1951.000000,0.000000,98033.000000,47.471000,-122.328000,1490.000000,5100.000000
50%,3.904930e+09,4.500000e+05,3.000000,2.250000,1910.000000,7.618000e+03,1.500000,0.000000,0.000000,3.000000,7.000000,1560.000000,0.000000,1975.000000,0.000000,98065.000000,47.571800,-122.230000,1840.000000,7620.000000
75%,7.308900e+09,6.450000e+05,4.000000,2.500000,2550.000000,1.068800e+04,2.000000,0.000000,0.000000,4.000000,8.000000,2210.000000,560.000000,1997.000000,0.000000,98118.000000,47.678000,-122.125000,2360.000000,10083.000000
max,9.900000e+09,7.700000e+06,33.000000,8.000000,13540.000000,1.651359e+06,3.500000,1.000000,4.000000,5.000000,13.000000,9410.000000,4820.000000,2015.000000,2015.000000,98199.000000,47.777600,-121.315000,6210.000000,871200.000000

In [15]:
df.describe().isnull()

,id,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
count,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
mean,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
std,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
min,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
25%,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
50%,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
75%,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
max,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21613 entries, 0 to 21612
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id             21613 non-null  int64
 1   date           21613 non-null  object
 2   price          21613 non-null  float64
 3   bedrooms       21613 non-null  int64
 4   bathrooms      21613 non-null  float64
 5   sqft_living    21613 non-null  int64
 6   sqft_lot       21613 non-null  int64
 7   floors         21613 non-null  float64
 8   waterfront     21613 non-null  int64
 9   view           21613 non-null  int64
 10  condition      21613 non-null  int64
 11  grade          21613 non-null  int64
 12  sqft_above     21613 non-null  int64
 13  sqft_basement  21613 non-null  int64
 14  yr_built       21613 non-null  int64
 15  yr_renovated   21613 non-null  int64
 16  zipcode        21613 non-null  int64
 17  lat            21613 non-null  float64
 18  long           21613 non-null  float64
 19  sqft_living15  21613 non-null  int64
 20  sqft_lot15     21613 non-null  int64
dtypes: float64(5), int64(15), object(1)
memory usage: 3.5+ MB

In [17]:
df.isnull().sum()

id               0
date             0
price            0
bedrooms         0
bathrooms        0
sqft_living      0
sqft_lot         0
floors           0
waterfront       0
view             0
condition        0
grade            0
sqft_above       0
sqft_basement    0
yr_built         0
yr_renovated     0
zipcode          0
lat              0
long             0
sqft_living15    0
sqft_lot15       0
dtype: int64

In [19]:
df.corr(numeric_only=True)['price'].sort_values(ascending=False)

price            1.000000
sqft_living      0.702035
grade            0.667434
sqft_above       0.605567
sqft_living15    0.585379
bathrooms        0.525138
view             0.397293
sqft_basement    0.323816
bedrooms         0.308350
lat              0.307003
waterfront       0.266369
floors           0.256794
yr_renovated     0.126434
sqft_lot         0.089661
sqft_lot15       0.082447
yr_built         0.054012
condition        0.036362
long             0.021626
id              -0.016762
zipcode         -0.053203
Name: price, dtype: float64

In [ ]:
from sklearn.linear_model import LinearRegression

X = df[['sqft_living']]
Y = df['price']

lm = LinearRegression()
lm.fit(X, Y)

print("R² =", lm.score(X, Y))

In [ ]:
features = ['floors',
            'waterfront',
            'lat',
            'bedrooms',
            'sqft_basement',
            'view',
            'bathrooms',
            'sqft_living15',
            'sqft_above',
            'grade',
            'sqft_living']

X = df[features]
Y = df['price']

lm = LinearRegression()
lm.fit(X, Y)

print("R² =", lm.score(X, Y))

In [ ]:
from sklearn.model_selection import train_test_split

Y = df['price']
X = df.drop('price', axis=1)

X = X.select_dtypes(include=['number'])

x_train, x_test, y_train, y_test = train_test_split(
    X, Y, test_size=0.15, random_state=1
)

print("Training set:", x_train.shape)
print("Testing set:", x_test.shape)

In [ ]:
from sklearn.linear_model import LinearRegression

lm = LinearRegression()
lm.fit(x_train, y_train)

print("Train R² =", lm.score(x_train, y_train))
print("Test R² =", lm.score(x_test, y_test))

In [ ]:
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

pr = PolynomialFeatures(degree=2)

x_train_pr = pr.fit_transform(x_train)
x_test_pr = pr.transform(x_test)

poly = LinearRegression()
poly.fit(x_train_pr, y_train)

pred = poly.predict(x_test_pr)

print("Polynomial Test R² =", r2_score(y_test, pred))

In [ ]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler, PolynomialFeatures
from sklearn.linear_model import LinearRegression

Input = [
    ('scale', StandardScaler()),
    ('polynomial', PolynomialFeatures(include_bias=False)),
    ('model', LinearRegression())
]

pipe = Pipeline(Input)

pipe.fit(X, Y)

print("Pipeline R² =", pipe.score(X, Y))

#R² = 0.8300